module.exports = Behavior({

  properties: {
    accesskey:{type:String},
    autocapitalize:{type:String},
    "data-*":{type:String},
    contenteditable:{type:Boolean},
    dir:{type:String},
    draggable:{type:Boolean},
    dropzone:{type:String},
    hidden:{type:Boolean},
    inputmode:{type:String},
    is:{type:String},
    itemid:{type:String},
    itemprop:{type:String},
    itemref:{type:String},
    itemscope:{type:String},
    itemtype:{type:String},
    slot:{type:String},
    tabindex:{type:Boolean},
    title:{type:String},
    lang:{type:String},
    spellcheck:{type:Boolean},
    tabindex:{type:Number},
    title:{type:String},
    translate:{type:Boolean},
  },
})